name: Build, Test Coveverage and Sonar

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Cache node_modules and coverage
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            coverage
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
  coverage:
    name: Test Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Cache node_modules and coverage
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            coverage
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Test Coverage
        run: npm run coverage
  sonar:
    name: Publish test coverage to sonar
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Cache node_modules and coverage
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            coverage
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Publish to sonar
      - uses: warchant/setup-sonar-scanner@v1
      - run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=4us-dev -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey=utils
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
